dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
install:
  - pip install -r requirements.txt
  - npm install dev
before_script:
  - npm start &
script:
  - npm test
notifications:
  email: false
