dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - npm install dev
before_script:
  - npm start &
  - sleep 3
script:
  - npm test
notifications:
  email: false
